#for ZED M
camera_model: "ZED_M"
camera_port: -1
camera0: 0
camera1: 1
#frame_width: 1280
#frame_height: 720
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 1
checkerboard_box_size_scale : 3.2
checkerboard_rows: 4
checkerboard_columns: 7
cooldown: 100
